Description: >
  circleci project.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: ec2_01 
      ImageId: ami-0c4f7023847b90238
      #ImageId: ami-06ebb7936bfa62864

      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y python3
          git clone https://github.com/Mohamed-Eleraki/CircleCI_training.git
          cd CircleCI_training/python/
          python3 main.py

          
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP traffic
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0  # Replace with your IP address or a specific CIDR block
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0  # Replace with your IP address or a specific CIDR block

