# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

parameters:
  release-tag:
    type: string
    default: " "
  boolean-tag:
    type: boolean
    default: false

jobs: 
  Build:  # Job Name
    docker:  # in this example will built our code in docker container, however you can use linux, macOS, etc..
      - image: cimg/python:3.11.3  # Spcecify The python image.
    steps:  # Job Steps
      - checkout  # checkout code from GitHub
      - run: python --version  # print out python version
      - run:
          name: "Build Python app"
          command: |
            cd python
            python3 main.py

      - run: mkdir -p workspace 
      - run: echo "Hello, Workspace" > workspace/echo-output

      - persist_to_workspace:
          root: workspace
          paths:
            - echo-output


  Scan_Build:  # Job Name
    docker:  # in this example will built our code in docker container, however you can use linux, macOS, etc..
      - image: cimg/python:3.11.3  # Spcecify The python image.
    steps:  # Job Steps
      - checkout  # checkout code from GitHub
      - run: python --version  # print out python version
      - run:
          name: "Scan Python app"
          command: |
            cd python
            python3 main_scan.py

      - attach_workspace:
          at: /tmp/workspace
      - run: cat  /tmp/workspace/echo-output
            
  Deploy:  # Job Name
    docker:  # in this example will built our code in docker container, however you can use linux, macOS, etc..
      - image: cimg/python:3.11.3  # Spcecify The python image.
    steps:  # Job Steps
      - checkout  # checkout code from GitHub
      - run: python --version  # print out python version
      - run:
          name: "Build Python app"
          command: |
            cd python
            python3 main.py 

      - attach_workspace:
          at: /tmp/workspace
      - run: cat  /tmp/workspace/echo-output

  Scan_Deploy:  # Job Name
    docker:  # in this example will built our code in docker container, however you can use linux, macOS, etc..
      - image: cimg/python:3.11.3  # Spcecify The python image.
    steps:  # Job Steps
      - checkout  # checkout code from GitHub
      - run: python --version  # print out python version
      - run:
          name: "Scan Python app"
          command: |
            cd python
            python3 main_scan.py

      - attach_workspace:
          at: /tmp/workspace
      - run: cat  /tmp/workspace/echo-output

            
# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  default:
    jobs:
      - Build

      - Scan_Build:
          requires: [Build]

      - Deploy:
          requires: [Build]

      - Scan_Deploy:
          requires: [Deploy, Scan_Build]

