version: 2.1

orbs:
  snyk: snyk/snyk@1.7.0

jobs:
 build_and_scan:

   machine:
    image: ubuntu-2204:2022.04.2
    docker_layer_caching: true 

   steps:
     - checkout

     # Login with credentials stored in the UI
     - run: 
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            #docker run -d --name monogdb mongo
            #docker ps

     # build the application image
     - run:
          name: Docker image build 
          command: |
            docker build -t webapp:$CIRCLE_BRANCH docker/.

     # deploy the image
     #- run: docker push webapp:$CIRCLE_BRANCH
     - run: 
          name: Push the image to DOCKER HUB
          command: |
            docker tag webapp:$CIRCLE_BRANCH mohamedibrahimeleraki/main:webapp1.1
            docker push mohamedibrahimeleraki/main:webapp1.1

workflows:
  Docker_Build_and_Scan:
    jobs:
      - build_and_scan

    