# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs: 
  Build:

    docker:
      - image: cimg/node:16.16.0
    resource_class: small

    steps:
      - checkout
      - run: npm install
     

workflows:
  python_App:
    jobs:
      - Build