version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  Build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - docker/build:
          image: nginx 
          debug: false 
          lint-dockerfile: false 
          treat-warnings-as-errors: false 
          use-buildkit: false 
          path: docker/Dockerfile 

workflows:
  Build_Docker:
    jobs:
      - Build

