# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs: 
  Build:

    docker:
      - image: cimg/base:stable
    resource_class: small 

    steps:
      - setup_remote_docker:
          docker_layer_caching: false
      - checkout
      - docker/check:
          - docker-password: DOCKER_PASSWORD
          - docker-username: DOCKER_LOGIN

workflows:
  Docker_Build:
    jobs:
      - Build:
          context:
            - Docker_Build_Context
