version: 2.1

orbs:
  snyk: snyk/snyk@1.7.0

executors:
   ubuntu-executor:
    machine:
      image: 'ubuntu-2204:2022.04.2'
    resource_class: small

jobs:
 build_and_scan:

   executor: ubuntu-executor
    
   steps:
     - checkout

     # Login with credentials stored in the UI
     - run: 
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            #docker run -d --name monogdb mongo
            #docker ps

     # build the application image
     - run:
          name: Docker image build 
          command: |
            docker build -t webapp:$CIRCLE_BRANCH docker/.

     # deploy the image
     #- run: docker push webapp:$CIRCLE_BRANCH
     - run: 
          name: Push the image to DOCKER HUB
          command: |
            docker tag webapp:$CIRCLE_BRANCH mohamedibrahimeleraki/main:webapp1.1
            docker push mohamedibrahimeleraki/main:webapp1.1

     # Container Scan
     - snyk/scan:
          fail-on-issues: true
          monitor-on-build: true



workflows:
  Nginx-webApp:
    jobs:
      - build_and_scan:
          context: Docker_Build_Context

    