version: 2.1

jobs:
 build:
   machine:
    image: ubuntu-2204:2022.04.2
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: |
         echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
         docker run -d --name monogdb mongo
         docker ps

     # build the application image
     - run: docker build -t webapp:$CIRCLE_BRANCH docker/.

     # deploy the image
     #- run: docker push webapp:$CIRCLE_BRANCH

     - run: |
         docker tag webapp:$CIRCLE_BRANCH mohamedibrahimeleraki/main:webapp1.1
         docker push mohamedibrahimeleraki/main:webapp1.1