# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs: 
  Build:

    docker:
      - image: cimg/python:3.11.4
    resource_class: small

    steps:
      - checkout
      #- run: pip install -r python/requirements.txt
      - python/install-packages:
          path: python/requirements.txt

      - run: python python/main.py
     

workflows:
  python_App:
    jobs:
      - Build