version: 2.1

orbs:
  snyk: snyk/snyk@1.7.0

executors:
   ubuntu_20-04-executor:
    machine:
      image: 'ubuntu-2204:2022.04.2'
      docker_layer_caching: true 

jobs:
 build:
    
   executor: ubuntu_20-04-executor

   steps:
     - checkout

     - restore_cache:
         keys: [nodeAppBuild]

     # Login with credentials stored in the UI
     - run: 
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin

     # build the application image
     - run:
          name: Docker image build 
          command: |
            docker build -t nodeapp:$CIRCLE_BRANCH docker/.
            docker images
     
     # Run the image in a container
     - run:
          name: Docker run
          command: |
            docker run -p 3000:3000 nodeapp:$CIRCLE_BRANCH
            docker ps

     # save cache
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild

 Test:
   executor: ubuntu_20-04-executor

   steps:
     - checkout

     - restore_cache:
         keys: [nodeAppBuild]

     - snyk/install
     - run:
         name: Snyk code test
         command: |
           snyk code test

     - run:
         name: Contianer test
         command: |
           # write down your test code here
           docker ps

     # save cache
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild


 Scan:
   executor: ubuntu_20-04-executor

   steps:
     - checkout

     - restore_cache:
         keys: [nodeAppBuild]

     - snyk/install

     # code scan
     - run:
         name: Snyk Code Scan
         command: |
           cd docker/node-package
           snyk test --file=./package.json
     
     # image scan
     - snyk/scan:
         docker-image-name: nodeapp:$CIRCLE_BRANCH
         fail-on-issues: false

     # save cache
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild


 Push-Image:
   executor: ubuntu_20-04-executor

   steps:
     - checkout

     - restore_cache:
         keys: [nodeAppBuild]

     # Push the image
     - run: 
          name: Push the image to DOCKER HUB
          command: |
            docker images
            docker tag nodeapp:$CIRCLE_BRANCH mohamedibrahimeleraki/main:node1.1
            docker push mohamedibrahimeleraki/main:node1.1

     # save cache
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild


workflows:
  Node-app:
    jobs:
      - build:
          context: Docker_Build_Context
      - Test:
          requires: [build]
          context: Docker_Build_Context
      - Scan:
          requires: [build]
          context: Docker_Build_Context
      - Push-Image:
          requires: [Scan, Test]
          context: Docker_Build_Context

