version: 2.1

orbs:
  snyk: snyk/snyk@1.7.0

executors:
   ubuntu_20-04-executor:
    machine:
      image: 'ubuntu-2204:2022.04.2'
      docker_layer_caching: true 

jobs:
 build_and_scan:
    
   executor: ubuntu_20-04-executor

   steps:
     - checkout

     # Login with credentials stored in the UI
     - run: 
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            #docker run -d --name monogdb mongo
            #docker ps

     # build the application image
     - run:
          name: Docker image build 
          command: |
            docker build -t node:$CIRCLE_BRANCH docker/.

     # deploy the image
     #- run: docker push node:$CIRCLE_BRANCH
     - run: 
          name: Push the image to DOCKER HUB
          command: |
            #docker tag node:$CIRCLE_BRANCH mohamedibrahimeleraki/main:node1.1
            #docker push mohamedibrahimeleraki/main:node1.1

     # Container Scan
     #- snyk/scan:
     #     fail-on-issues: true
     #     monitor-on-build: true #


     - snyk/install
     - run:
         name: Snyk Scan
         command: |
           cd docker/node-package
           snyk test --file=./package.json

     - run:
         name: Snyk test
         command: |
           snyk code test

 scan:
   executor: ubuntu_20-04-executor

   steps:
     - checkout
     - run:
         name: Snyk test
         command: |
           snyk code test


workflows:
  Node-app:
    jobs:
      - build_and_scan:
          context: Docker_Build_Context
      - scan:
          context: Docker_Build_Context
    