version: 2.1

orbs:
  docker: circleci/docker@2.1.4

jobs:
  Build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true

      - docker/check:
          docker-password: DOCKER_PASSWORD
          docker-username: DOCKER_LOGIN


workflows:
  Build_Docker:
    jobs:
      - Build:
          context:
            - Docker_Build_Context


