version: 2.1

orbs:
  docker: circleci/node@5.1.0

jobs:
  Build_and_test:

    docker:
      - image: cimg/node:16.16.0

    steps:
      - checkout
      - node/install-packages

      - run:
          name: run tests
          command: npm run test-ci

      - run: 
          name: copy tests result for storing
          command: |
            mkdir test-result
            cp test-result.xml test-result/
          when: always

      - store_test_result:
          path: test-result
workflows:
  Build_Docker:
    jobs:
      - Build_and_test


