# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs: 
  Build:

    docker:
      - image: cimg/python:3.11.4
    resource_class: small

    steps:
      - checkout
      #- run: pip install -r python/requirements.txt
      - python/install-packages:
          pkg-manager: pip

      - python/install-packages:
          pkg-manager: pip
          app-dir: python/  # If your requirements.txt isn't in the root directory.
          args: pytest
          pypi-cache: false
      - run:
          name: Test
          command: |
            pytest python/main.py


      - run: python python/main.py

      #- python/test:
      #    args: '--dev'
      #    pkg-manager: pipenv
      #    test-tool: pytest

      #- run: 
      #    name: copy tests result for storing
      #    command: |
      #      mkdir test_results
      #      cp -r test-results.xml test_results/
      #    when: always

      - store_test_results:
          path: test-results      

workflows:
  python_App:
    jobs:
      - Build
