version: 2.1

# Define snyk orb for code scanning
orbs:
  snyk: snyk/snyk@1.7.0

# Defince executor machine as a parameter
executors:
   ubuntu_20-04-executor:
    machine:
      image: 'ubuntu-2204:2022.04.2'
      docker_layer_caching: true 

jobs:

# Build docker image job
 build-image:
   
   # Fetch the executor defined above
   executor: ubuntu_20-04-executor


   steps:

     - checkout  # code checkout from repo

     - restore_cache:
         keys: [nodeAppBuild]

     # Login with credentials stored in the UI "context"
     - run: 
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin

     # build the application image
     - run:
          name: Docker image build 
          command: |
            docker build -t nodeapp:$CIRCLE_BRANCH docker/.
            docker images
     
     # Run the image in a container
     - run:
          name: Docker run
          command: |
            docker run -p 3000:3000 nodeapp:$CIRCLE_BRANCH
            docker ps

     # save cache, to use the built image in the next jobs for testing and scaning
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild

 Test:

   # Fetch the executor defined above
   executor: ubuntu_20-04-executor

   steps:

     - checkout

     - restore_cache:
         keys: [nodeAppBuild]


     - run:  # here type your own code for testing the application
         name: Contianer test
         command: |
           # write down your test code here
           docker images

     # save cache
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild


 Scan:

   # Fetch the executor defined above
   executor: ubuntu_20-04-executor

   steps:
     - checkout

     - restore_cache:
         keys: [nodeAppBuild]

     # Install the snyk command using the snyk orb definced above
     - snyk/install

     # Project code scan
     - run:
         name: Snyk code test
         command: |
           snyk code test

     # package file code scan
     - run:
         name: Snyk Code Scan
         command: |
           cd docker/node-package
           snyk test --file=./package.json
     
     # image scan
     - snyk/scan:
         docker-image-name: nodeapp:$CIRCLE_BRANCH
         fail-on-issues: false

     # save cache
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild


 Push-Image:

   # Fetch the executor defined above
   executor: ubuntu_20-04-executor

   steps:

     - checkout

     - restore_cache:
         keys: [nodeAppBuild]

     # Login with credentials stored in the UI "context"
     - run: 
          name: Docker login
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin

     # Push the image
     - run: 
          name: Push the image to DOCKER HUB
          command: |
            docker images
            docker tag nodeapp:$CIRCLE_BRANCH mohamedibrahimeleraki/main:node1.1
            docker push mohamedibrahimeleraki/main:node1.1

     # save cache
     - save_cache:
         paths: [docker/save_cache]
         key: nodeAppBuild


workflows:
  Node-app:
    jobs:
      - build-image:
          context: Docker_Build_Context  # fetch the environment variables from the context
      - Test:
          requires: [build-image]
          context: Docker_Build_Context  # fetch the environment variables from the context
      - Scan:
          requires: [Test]
          context: Docker_Build_Context  # fetch the environment variables from the context
      - Push-Image:
          requires: [Scan]
          context: Docker_Build_Context  # fetch the environment variables from the context

