# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

jobs: 
  Build:

    docker:
      - image: cimg/python:3.11.4
    resource_class: small

    steps:
      - checkout

      - restore_cache:
          keys: [pythonAppBuild]
          
      - run: pip install -r python/requirements.txt
      - run: python python/main.py

      - save_cache:
          paths: [python/save_cache]
          key: pythonAppBuild
workflows:
  python_App:
    jobs:
      - Build