version: 2.1

orbs:
  docker: circleci/docker@2.2.0

jobs:
  Build:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - run: ls; pwd
      #- docker/check
      - docker/build:
          dockerfile: docker/Dockerfile
          image: nginx

workflows:
  Build_Docker:
    jobs:
      - Build





#jobs: 
#  Build:
#
#    docker:
#      - image: cimg/base:stable
#
#    steps:
#      - checkout
#      - setup_remote_docker
#      #- use-docker-credentials-store: true
#      - docker/check:
#          - docker-password: DOCKER_PASSWORD
#          - docker-username: DOCKER_LOGIN
#
#workflows:
#  Docker_Build:
#    jobs:
#      - Build:
#          context:
#            - Docker_Build_Context
